import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AgletSans } from "../styles/font";
import Head from "next/head";
import { Container } from "@/styled-system/jsx";
import { css } from "@/styled-system/css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${AgletSans.variable}`}>
      {/* <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <body className={inter.className}>
        <div
          className={css({
            display: "flex",
            minHeight: "100vh",
          })}
        >
          <div className={css({ width: "full" })}>{children}</div>
        </div>
      </body>
    </html>
  );
}
